CREATE TABLE IF NOT EXISTS FILMS
(
    film_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255) NOT NULL,
    description  TEXT         NOT NULL,
    release_Date DATE         NOT NULL,
    duration     INTEGER      NOT NULL,
    rating_id    INTEGER      NOT NULL
);

CREATE TABLE IF NOT EXISTS USERS
(
    user_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    VARCHAR(255) NOT NULL,
    login    VARCHAR(255) NOT NULL,
    name     VARCHAR(255) NOT NULL,
    birthday DATE         NOT NULL
);

CREATE TABLE IF NOT EXISTS FRIENDSHIP
(
    friend_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_invite INTEGER NOT NULL,
    user_take   INTEGER NOT NULL
--     status_id   INTEGER NOT NULL
);
-- ALTER TABLE
--     FRIENDSHIP
--     ADD PRIMARY KEY (friend_id);
CREATE TABLE IF NOT EXISTS LIKES
(
    like_id INTEGER NOT NULL,
    film_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL
);
ALTER TABLE
    LIKES
    ADD PRIMARY KEY (like_id);
CREATE TABLE IF NOT EXISTS GENRES
(
    genre_id INTEGER      NOT NULL,
    name     VARCHAR(255) NOT NULL
);
ALTER TABLE
    GENRES
    ADD PRIMARY KEY (genre_id);
CREATE TABLE IF NOT EXISTS GENRE_FILM
(
    genre_Film_id INTEGER NOT NULL,
    film_id       INTEGER NOT NULL,
    genre_id      INTEGER NOT NULL
);
ALTER TABLE
    GENRE_FILM
    ADD PRIMARY KEY (genre_Film_id);
CREATE TABLE IF NOT EXISTS RATING_MPA
(
    rating_id       INTEGER      NOT NULL,
    rating_mpa_name VARCHAR(255) NOT NULL
);
ALTER TABLE
    RATING_MPA
    ADD PRIMARY KEY (rating_id);

-- CREATE TABLE IF NOT EXISTS FRIENDSHIP_STATUS
-- (
--     status_id   INTEGER NOT NULL,
--     description INTEGER NOT NULL
-- );
--
-- ALTER TABLE
--     FRIENDSHIP_STATUS
--     ADD PRIMARY KEY (status_id);

ALTER TABLE
    GENRE_FILM
    ADD CONSTRAINT "genre_film_film_id_foreign" FOREIGN KEY (film_id) REFERENCES FILMS (film_id);

ALTER TABLE
    LIKES
    ADD CONSTRAINT "likes_film_id_foreign" FOREIGN KEY (film_id) REFERENCES FILMS (film_id);
ALTER TABLE
    FILMS
    ADD CONSTRAINT "films_rating_id_foreign" FOREIGN KEY (rating_id) REFERENCES RATING_MPA (rating_id);
ALTER TABLE
    FRIENDSHIP
    ADD CONSTRAINT "friendship_user_invite_foreign" FOREIGN KEY (user_invite) REFERENCES USERS (user_id);
ALTER TABLE
    FRIENDSHIP
    ADD CONSTRAINT "friendship_user_take_foreign" FOREIGN KEY (user_take) REFERENCES USERS (user_id);
ALTER TABLE
    LIKES
    ADD CONSTRAINT "likes_user_id_foreign" FOREIGN KEY (user_id) REFERENCES USERS (user_id);
ALTER TABLE
    GENRE_FILM
    ADD CONSTRAINT "genre_film_genre_id_foreign" FOREIGN KEY (genre_id) REFERENCES GENRES (genre_id);
-- ALTER TABLE
--     FRIENDSHIP
--     ADD CONSTRAINT "friendship_status_id_foreign" FOREIGN KEY (status_id) REFERENCES FRIENDSHIP_STATUS (status_id);